apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: mysql
        image: 547747823946.dkr.ecr.us-east-1.amazonaws.com/mysql-assignment2:latest
        ports:
        - containerPort: 3306
        env:
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
      imagePullSecrets:
      - name: mysecret
