apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  containers:
  - name: application-container
    image: 547747823946.dkr.ecr.us-east-1.amazonaws.com/webapp-assignment2:latest
    ports:
    - containerPort: 8080
    env:
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: DBPORT
      value: "3306"
  imagePullSecrets:
  - name: mysecret
